version: '3'
services:
  gateway:
    build:
      context: gateway
    image: steveww/splunk-gateway
    ports:
      - "8080:8080"
    networks:
      - gateway-net
    environment:
      GATEWAY_SPLUNK_URL: 'https://foo.splunk.com/v1/'
      GATEWAY_SPLUNK_KEY: 'password'
      GATEWAY_SERVER_PORT: 8080


networks:
  gateway-net:

